### ISSUE TITLE
IntelOwl v5.0.1 not connecting to OpenCTI

### ISSUE THREAD

**Issue by nebu10uz** [intelowlproject/IntelOwl#1730] opened 2023-06-05 16:14 UTC
## What happened
IntelOwl v5.0.1 not connecting to OpenCTI

## Environment
1. OS: Ubuntu 22.04
2. IntelOwl version: 5.0.1

##  What did you expect to happen
Successful connection to OpenCTI.

## How to reproduce your issue
Configure your OpenCTI connector plugin using your `api_key_name `and `url_key_name.` Note, my OpenCTI server is using a custom port, therefore, my `url_key_name `configuration looks like this: http://myopencti.local:8080. Not sure if this is the issue. Can the `url_key_name` take custom ports?
## Error messages and logs
![image](https://github.com/intelowlproject/IntelOwl/assets/1797583/2150d002-ebbb-4e32-8d09-e26a0eff4b35)

Additional info:
I configured my OpenCTI connector plugin based on this https://github.com/intelowlproject/IntelOwl/issues/924. Additionally, I connected to my IntelOwl server and performed a "HEAD" HTTP request using curl and I received a `HTTP/1.1 200 OK` response so the server is reaching to my OpenCTI server.

![image](https://github.com/intelowlproject/IntelOwl/assets/1797583/faf88a2a-a53b-4afc-baed-42b06cdffc7c)

**Comment by nebu10uz** [comment] 2023-06-05 18:27
> thanks for reporting. The data you provided is useful.
> 
> We use the official OpenCTI python library. I quickly checked that code and it should handle the port number. The library version instsalled in IntelOwl is 5.7.3 while the available one is 5.7.6. I dont know if that's the problem but could be. Another thing: which version of OpenCTI are you using? If that's old, there could be no compatibility.
> 
> Have you tried to run an analysis with that connector enabled and see if that works? I don't have an OpenCTI instance available for such testing now. Cause it could be a problem of the health check only considering that you showed me that the HEAD request work as expected.
> 
> If you can provide me the `/var/lib/docker/volumes/intel_owl_generic_logs/_data/django/api_app.log` log maybe I find something useful

I'm using the latest version of OpenCTI v5.7.6. And yes, I tried to analyze an IP and selected the OpenCTI connector and based on the API logs, the OpenCTI API is not reachalbe:

![image](https://github.com/intelowlproject/IntelOwl/assets/1797583/9292fa4c-b075-460f-8c85-80efd7d3b0ee)

**Comment by nebu10uz** [comment] 2023-06-05 19:07
It's possible that the OpenCTI API code in IntelOwl must be updated to 5.7.6 in order to work:

![image](https://github.com/intelowlproject/IntelOwl/assets/1797583/dcdb184a-1e60-4152-898f-8592ad911732)

**Comment by nebu10uz** [comment] 2023-06-05 20:02
Ok, I found this issue on OpenCTI https://github.com/OpenCTI-Platform/docker/issues/49. I will investigate and report back. Looks like I need to configure and validate on the OpenCTI server side.

**Comment by nebu10uz** [comment] 2023-06-05 23:20
Nope, based on the above OpenCTI issue I couldn't get it to work.

Now, based on this other OpenCTI issue https://github.com/OpenCTI-Platform/connectors/issues/205 it appears that the OpenCTI API version has to match.

**Comment by nebu10uz** [comment] 2023-06-05 23:35
So I imagine this could be probably be fixed by changing the following variable from pycti==5.7.3 to pycti==5.7.6 on this file: https://github.com/intelowlproject/IntelOwl/blob/master/requirements/project-requirements.txt.

**Comment by mlodic** [comment] 2023-06-06 08:45
Ah the health check could still not work, we'll fix it in the next release

**Comment by nebu10uz** [comment] 2023-06-07 02:13
I configured the parameter to false but I'm still getting the same error message. 

I'll try again once the pycti is updated to the latest version.

Thanks or all the help!

**Comment by 0ssigeno** [comment] 2023-06-20 08:58
@nebu10uz pycti was updated to `5.8.2` if you want to give another try to the connector

**Comment by nebu10uz** [comment] 2023-06-20 16:14
> @nebu10uz pycti was updated to `5.8.2` if you want to give another try to the connector

Ok, I will try when I get a chance and report back.

Thanks!

**Comment by mlodic** [comment] 2023-08-14 15:34
is this still a problem?

**Comment by mlodic** [comment] 2023-08-29 08:49
Thank you for the catch-up!

Right now I don't have any decent idea about how to help the users in that sense. The problem is clearly on the pycti side so we would need to find a workaround.

One thing that I don't really like but we already did for people who wanted to change the py-elasticsearch version is to:
* provide a base version, the most recent one. And that's fine, like we do now
* give the chance to the users to select the right OpenCTI version that they need by manually changing the Dockerfile and then have them re-build IntelOwl locally with the right OpenCTI version

In this way you can install your own version but that would require some additional manual work and build from the users. Better than having no chance to do that at all I guess.

**Comment by ashcorpdev** [comment] 2023-08-29 08:53
I agree that this would likely be the easiest solution (with a note in the documentation, of course).

It seems like OpenCTI does update (fairly) regularly, and thus, this would make sure that those users who are moving to latest versions would still be able to use IntelOwl effectively, and drops the requirement for you to keep up with their update schedule, as you have mentioned.

**Comment by mlodic** [comment] 2023-08-29 13:44
With the new option I am adding, users would be able to use the option `--pycti-version` with the `start.py` script to select the pycti version to use while builiding a new image for IntelOwl. I have documented it all thoroughfully. Will be released at the next cycle soon. Hope that helps

**Comment by mlodic** [comment] 2023-12-29 15:36
closing due to no other issues arised

**Closed by mlodic** 2023-12-29 15:36 UTC
Labels: bug
