### ISSUE TITLE
Error when trying to run with AWS Secrets Manager

### ISSUE THREAD

**Issue by arakakiv** [intelowlproject/IntelOwl#2540] opened 2024-10-16 20:22 UTC
## What happened
When executing the container _intel_owl_uwsgi_, an error occurs indicating that the settings object lacks the AWS_REGION key. I initially thought I hadn’t passed the environment variable, but I followed step by step the docs. I set up AWS_REGION, the necessary credentials (access keys or AWS_IAM_ACCESS), and AWS_SECRETS environment variables, both in the AWS infrastructure and locally with access keys. Additionally, I tried setting these variables both by manually exporting them in the shell and using the _env_file_app_ file.

## Environment
1. OS: Ubuntu LTS 22.04
2. IntelOwl version: v6.1.0

##  What did you expect to happen
Retrieve my AWS secrets from the AWS Secrets Manager service.

## How to reproduce your issue
1. Run the `initialize.sh` script.
2. Set up the `AWS_REGION`, `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and the `AWS_SECRETS` environment variables in the `env_file_app`.
3. Run the `./start prod up` command.

## Error messages and logs
The error basically says that the settings object doesn't have the AWS_REGION key. I look at the code and in the `secrets.py` file, but I couldn't understand why the error is occurring. It looks like occurs when running the `manage.py` script, but I can be wrong.

![Error](https://github.com/user-attachments/assets/dbadb264-16ae-4ce4-9fc0-a843727c8f66)

**Comment by mlodic** [comment] 2024-10-21 15:53
hey, thanks for reporting. I opened a PR https://github.com/intelowlproject/IntelOwl/pull/2541/files. It should be fixed into the next release

**Comment by arakakiv** [comment] 2024-10-21 16:40
> hey, thanks for reporting. I opened a PR https://github.com/intelowlproject/IntelOwl/pull/2541/files. It should be fixed into the next release

I really appreciate your response, thanks. The whole problem was that it wasn't possible to retrieve the AWS_REGION variable from the django settings? Why I wasn't being able to modify the code and run it? Did I did something wrong?

*I was modifying the source code and trying to run the `start` script.

**Comment by arakakiv** [comment] 2024-10-21 19:39
> hey, thanks for reporting. I opened a PR https://github.com/intelowlproject/IntelOwl/pull/2541/files. It should be fixed into the next release

Also, I cloned the branch but I couldn't make it work as well. Is there any steps that I'm missing based on what I provided on the issue description?

**Comment by mlodic** [comment] 2024-10-22 07:34
yep, the problem was that the AWS_REGION variable was accessed before being populated. (I still have to verify if the PR actually works as intended, so give me some time and I'll finish the PR and put it in the `develop` branch which is the official development branch. Then you can try it even before our official releases)

If you modify the source code or run a branch of IntelOwl other than `master` you should then execute it with the start script with the option `test` instead of `prod`. In this way the local code would be used instead of the latest official version. Could this be the case?

**Comment by mlodic** [comment] 2024-10-22 10:43
ok you can try from the `develop` branch now, it should work

**Comment by arakakiv** [comment] 2024-10-22 11:20
> yep, the problem was that the AWS_REGION variable was accessed before being populated. (I still have to verify if the PR actually works as intended, so give me some time and I'll finish the PR and put it in the `develop` branch which is the official development branch. Then you can try it even before our official releases)
> 
> If you modify the source code or run a branch of IntelOwl other than `master` you should then execute IntelOwl with the start script with the option `test` instead of `prod`. In this way the local code would be used instead of the latest official version. Could this be the case?

Hi.

This is probably on the docs, I'm sorry about it, I thought that modifying the code would be enough. Today I'll try the develop branch and use the `test` option.

Thanks again for the help and the quick responses, you're helping a lot.

**Comment by arakakiv** [comment] 2024-10-24 17:41
Hello again.

The fix was successful. How long would it take to release a new production version with this fix? 

Thanks!

**Comment by mlodic** [comment] 2024-10-25 13:16
at the moment we manage public releases on best efforts (the service is for free) so we are trying to prioritize them based on requests like this one. I'll try to move the next one forward as soon as I can

**Closed by mlodic** 2024-10-25 13:16 UTC
Labels: bug

**Comment by arakakiv** [comment] 2024-10-25 14:58
Thanks a lot!
