### ISSUE TITLE
New connector - Maltego

### ISSUE THREAD

**Issue by eshaan7** [intelowlproject/IntelOwl#847] opened 2022-01-12 06:00 UTC
https://www.maltego.com/

https://github.com/paterva/maltego-trx
https://github.com/cmlh/MaltegoTransform-Python
(not sure if these libraries are what we want)

----------------
Note: may or may not be "beginner-friendly"

**Comment by CypherpunkSamurai** [comment] 2022-01-12 18:00
Hello Sir, I've been an OSINT CTF player in the past and I feel interested in working on this issue. Can I please work on this?

**Comment by mlodic** [comment] 2022-01-13 10:35
you have already 3 open PRs. We will assing you other issues once all of those are finished.

**Comment by CypherpunkSamurai** [comment] 2022-01-13 16:15
Ok Sir 👍🏼

**Comment by devmrfitz** [comment] 2022-02-16 07:04
I would like to work on this. Is the description of the issue up to date or does something need to be added before I start?

**Comment by mlodic** [comment] 2022-02-16 09:48
I have removed `beginner-friendly` because this requires serious understading of how Maltego works. @devmrfitz have you ever tried that tool?

**Comment by CypherpunkSamurai** [comment] 2022-02-16 17:36
> I would like to work on this. Is the description of the issue up to date or does something need to be added before I start?

The description is up to date, you may start working on it as soon as you're assigned :)

As Mr. Mlodic said, you need to have a prior understanding of the Maltego tool and also get an idea of how a new connector would help the project. If you got both of these in check you're good to go! If you get stuck feel free to message here on the issue, or IntelOwl slack :)

alternatively, as a beginner-friendly alternative feel free to work on Cyberchef issue 834. Every little contribution helps the project! :D

**Comment by devmrfitz** [comment] 2022-02-16 17:54
@mlodic No, I do not have prior experience with Maltego. However, I'm willing to spend the time to figure it out. However, if you feel it would be impractical, I could look into Cyberchef #843, (as @CypherpunkSamurai helpfully pointed me to). What would you recommend?

**Comment by mlodic** [comment] 2022-02-16 18:22
this makes sense, that is easier for sure

**Comment by CypherpunkSamurai** [comment] 2022-02-23 18:27
Hello Sir, My 2 PR's have been merged successfully :)

Can I please takeover this issue now?

**Comment by CypherpunkSamurai** [comment] 2022-03-01 15:02
Hello Mr @eshaan7 and Mr @mlodic,
I'm sorry for the delay, I had been busy with my college studies for some time. With due respect I wanted to ask a few questions.

With Maltego being an offline file-based data store, are we supposed to make a new maltego graph file with transforms?

**Comment by CypherpunkSamurai** [comment] 2022-03-10 19:01
It looks like Maltego requires a paid subscription to allow third-party seeds. I'm using the Free version, so no luck. I won't be able to write a sample connector.

![image](https://user-images.githubusercontent.com/66906402/157735751-27205846-6389-4c20-b252-474b0fcfb361.png)

![image](https://user-images.githubusercontent.com/66906402/157735568-823e40dd-9bb9-4135-9850-ab6db794593f.png)

**Comment by mlodic** [comment] 2022-03-11 07:47
I'd say that if we don't find out a way to have a "free" integration we can just drop the idea. Anyway, can you please explain what you find out about Maltego and what you exactly were trying to achieve there? thanks

**Comment by CypherpunkSamurai** [comment] 2022-03-11 08:23
Ok Sir.

I found out that TRX is a rest API-type server that allows running maltego transforms remotely. We can use the TRX server by adding its transforms as TRX transforms. This allows maltego to make a simple HTTP request and run a remote transform and return data to the graph.

The problem is, to use a remote TRX server we need a paid version of maltego.

**Comment by mlodic** [comment] 2022-03-11 08:54
well makes sense. Thanks for your research. I am sorry that, at this point, we will drop the issue. IntelOwl main goal is to provide free tools and do not support paid-only services so this is not something we care about

**Closed by mlodic** 2022-03-11 08:54 UTC
Labels: new_connector

**Comment by CypherpunkSamurai** [comment] 2022-03-11 09:14
No problem Sir. I'm happy we explored the possibility of having a maltego integration. I've learnt a lot about maltego on the way, thanks to you and Mr Eshaan
