### ISSUE TITLE
Add OpenCTI

### ISSUE THREAD

**Issue by vxsh4d0w** [intelowlproject/IntelOwl#158] opened 2020-08-19 16:06 UTC
Adding OpenCTI as integrated tool could be an opportunity to share ifo between two platform. In particulare IntelOwl could extract all info about artifacts and export this info to OpenCti where an analyst could enrich with other details. or import from OpenCti other info already available.

**Comment by Eshaan7** [comment] 2020-08-19 16:08
Duplicate of #11.

**Closed** 2020-08-19 16:24 UTC

**Comment by vxsh4d0w** [comment] 2020-08-19 16:27
👍

**Comment by mlodic** [comment] 2020-08-20 06:47
Thank you for your inputs @vxsh4d0w! 

The fact that your ideas were already integrated or are already planned means that we are following the right path! This is exactly what we would like to hear from the community!
