### ISSUE TITLE
IntelOwl not working opencti anymore

### ISSUE THREAD

**Issue by alfwazi** [intelowlproject/IntelOwl#1224] opened 2022-10-04 17:37 UTC
## What happened
After upgrading OPENCTI to 5.3.16 , we suddenly get an error when we use opencti connector

## Environment
1. OS: Ubuntu
2. IntelOwl version: 4.0.1

##  What did you expect to happen
Send the report normally to the OPENCTI as usual
## How to reproduce your issue
when IntelOwl try to send a report to the OPENCTI connector
## Error messages and logs

intelowl_celery_worker_default | [2022-10-04 16:41:07,581: ERROR/ForkPoolWorker-11] Variable "$stix_id" of type "String" used in position expecting type "StixId".

Kindly note that OPENCTI team added the below feature to their new versions which triggered this issue 

**the format of the STIX IDs (and internal IDs) is now verified before ingestion and creation of objects .**

**Comment by mlodic** [comment] 2022-10-05 16:43
hey, do you have any link to their documentation or some other info about that change?

We struggle to make tests with opencti, so we would need full support to solve this to make it work. If you know where the error is please submit a pull request

**Comment by sercuz** [comment] 2022-10-09 09:19
Hey, I have the same issue. I will help here

**Comment by sercuz** [comment] 2022-10-09 09:27
I believe the changes happened since this version https://github.com/OpenCTI-Platform/opencti/releases/tag/5.3.12
They have change the string data type to be stixid data type. 
"If you have developed connectors that directly call the API through GraphQL, you will have to migrate some query definitions from string type to StixId type." - release note 5.3.12

**Comment by mlodic** [comment] 2022-10-13 09:01
could you please point me out where is the error in the code considered that you faced those errors? I need the full stack trace cause I don't have an updated opencti instance ready to test it. Thank you

**Comment by mlodic** [comment] 2022-10-13 09:02
I am trying to help you @alfwazi but I need you to collaborate on this otherwise I won't be able to fix this soon

**Comment by sercuz** [comment] 2022-10-13 09:50
Hi @mlodic ,
I believe the issue is in the data type in the definitions below. I think it must be **stixId** data type as they mentioned in OpenCTI release notes. https://github.com/OpenCTI-Platform/opencti/releases/tag/5.3.12


![image](https://user-images.githubusercontent.com/62757007/195564328-a724f224-02cf-49c9-92f4-828f9f9e0f80.png)

**Comment by mlodic** [comment] 2022-10-13 10:21
thank you but I don't know what is the stixId data type in OpenCTI , how to generate one and how it is used there.

This integration was developed by a contributor and I don't have advanced knowledge of the platform

**Comment by mlodic** [comment] 2022-10-13 10:23
@nor3th could you please help us in solving this?

**Comment by sercuz** [comment] 2022-10-13 10:23
Anytime, I think it is STIX version 3 data type. It is not special data type for OpenCTI.

**Comment by mlodic** [comment] 2022-10-13 10:25
yeah but `you will have to migrate some query definitions from string type to StixId type` means that I have to move strings to stixId. But where? Cause INTELOWL_OPENCTI_TYPE_MAP does not contain `string` types.
If I only have the line when this error is triggered, that would be easy to fix

**Comment by sercuz** [comment] 2022-10-13 10:27
Thank you @mlodic for your support. @nor3th I would like to help here if you need anything.

**Comment by nor3th** [comment] 2022-10-13 15:47
Hey 

That's an error the platform returns to the client, since the client (pycti) used the old id format in its query. This shouldn't require any modifications from your side, as you are only using the ids which pycti returns. Try updating the requirements to the most recent version (5.3.17) and then have a go at it.

Regards

**Comment by mlodic** [comment] 2022-10-13 16:19
hey @nor3th , thank you very much for the fast answer! I have just updated the dependency and will make it available in the next release!

**Comment by sercuz** [comment] 2022-10-13 18:43
hey all, thank you @mlodic & @nor3th for you support.

**Comment by mlodic** [comment] 2022-11-10 18:27
since the last version, this should work so I close this.

**Closed by mlodic** 2022-11-10 18:27 UTC
Labels: bug
