### ISSUE TITLE
observable_name forced to lowercase issue with shortened URLs

### ISSUE THREAD

**Issue by j0n3z** [intelowlproject/IntelOwl#931] opened 2022-03-14 03:12 UTC
## What happened
In https://github.com/intelowlproject/IntelOwl/issues/658, there was an issue with hash observable and needed to be converted to lower case. However, the fix affected other observable like URLs. Some URLs may need to be looked up without converting to lower case.

## Environment
1. OS: Linux
2. IntelOwl version: current release

##  What did you expect to happen
URL need not to be converted to lower case.

## How to reproduce your issue
Get any shortened URL with at least one capital letter: ie: https://bit.ly/3q24itB
Converting the upper case letter to lowercase will not lead to the shortened URL.

**Comment by mlodic** [comment] 2022-03-14 10:11
oh good catch! We'll fix this!

**Comment by mlodic** [comment] 2022-03-14 10:39
I made a fix here: https://github.com/intelowlproject/IntelOwl/pull/856/commits/b8d842457f12f2301fa44833460463bbf26521d9

I just left forcing the observable to lower case only for "hash" types. In this way URL won't be affected. This will be available with the new v4 major release (~a month)

**Comment by j0n3z** [comment] 2022-03-14 11:27
Awesome!

**Comment by eshaan7** [comment] 2022-03-15 09:23
Thanks for the bug report! 

We decided that this is a high-priority bug so the fix for this will be included in the upcoming patch release (and not v4.0 as mentioned before) within the next few days.

**Comment by mlodic** [comment] 2022-03-15 09:26
the problem is that the database handles the observables by their related calculated hash (md5). If we allow users to insert domains with capital letters then we would need to normalize them like we make for the hashes so they can be considered as the same observable by the database.
So we can allow domains with capital letters (we call `lower()` after evaluation so they are considered the same as the lowercase ones) but we can't do that for full URL for the reason you mentioned. I'll push another fix and, as @eshaan7 said, create a new release in few days

**Closed** 2022-03-25 09:26 UTC
Labels: bug
